Добавил контроллер и пару методов
Timqa/letinstagram pull request #2
Opened 2022-03-19 17:44 UTC by Timqa

2022-03-19 22:08 UTC, LazyTechwork requested changes

2022-03-19 22:08 UTC, LazyTechwork commented on app/Http/Controllers/MainController.php
> +      return view('welcome', );
Тут второй аргумент не передан, но запятая есть, компилятор не должен был пропустить

2022-03-20 06:16 UTC, Timqa commented on app/Http/Controllers/MainController.php
> +      return view('welcome', );
исправлю и заного ПР сделать?

2022-03-20 20:12 UTC, LazyTechwork commented on app/Http/Controllers/MainController.php
> +      return view('welcome', );
PR новый не надо, коммить в эту же ветку, PR обновится

2022-03-20 20:13 UTC, LazyTechwork approved these changes
Можешь отправлять ДЗ на сайте, я приму

2022-03-20 20:13 UTC, merged